# -*- coding: utf-8 -*-
"""dynamic-pricing-engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vqi3gdeKRR0F6i9eWOAS_Doubi4aqb-p
"""

# ===============================
# 1. IMPORT LIBRARIES
# ===============================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error

import matplotlib.pyplot as plt
import pickle

# ===============================
# 2. LOAD DATASET
# ===============================
df = pd.read_csv("/content/dynamic_pricing.csv")

print("Dataset Shape:", df.shape)
print(df.head())

# ===============================
# 3. ENCODE CATEGORICAL COLUMNS
# ===============================
le = LabelEncoder()

categorical_cols = [
    "Location_Category",
    "Customer_Loyalty_Status",
    "Time_of_Booking",
    "Vehicle_Type"
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

# ===============================
# 4. FEATURE ENGINEERING (IMPORTANT 🔥)
# ===============================
df["Demand_Supply_Ratio"] = df["Number_of_Riders"] / df["Number_of_Drivers"]
df["Price_Per_Duration"] = df["Historical_Cost_of_Ride"] / df["Expected_Ride_Duration"]

# ===============================
# 5. DEFINE FEATURES & TARGET
# ===============================
X = df.drop("Historical_Cost_of_Ride", axis=1)
y = df["Historical_Cost_of_Ride"]

# ===============================
# 6. TRAIN TEST SPLIT
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===============================
# 7. TRAIN MODEL
# ===============================
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# ===============================
# 8. PREDICTION
# ===============================
preds = model.predict(X_test)

# ===============================
# 9. EVALUATION
# ===============================
mae = mean_absolute_error(y_test, preds)
print("\nModel MAE:", round(mae, 2))

# ===============================
# 10. SMART PRICING LOGIC 🔥
# ===============================
predicted = model.predict(X)

# Apply demand-supply based pricing adjustment
df["Adjusted_Price"] = predicted * (1 + 0.05 * df["Demand_Supply_Ratio"])

# Add cap (important)
df["Adjusted_Price"] = df["Adjusted_Price"].clip(
    lower=predicted * 0.8,
    upper=predicted * 1.2
)

df["Predicted_Price"] = df["Adjusted_Price"]

# ===============================
# 11. REVENUE SIMULATION 🔥🔥
# ===============================
df["Old_Revenue"] = df["Number_of_Riders"] * df["Historical_Cost_of_Ride"]
df["New_Revenue"] = df["Number_of_Riders"] * df["Predicted_Price"]

improvement = (
    (df["New_Revenue"].sum() - df["Old_Revenue"].sum())
    / df["Old_Revenue"].sum()
) * 100

print("Revenue Improvement:", round(improvement, 2), "%")

# ===============================
# 12. FEATURE IMPORTANCE (BONUS)
# ===============================
importance = model.feature_importances_
features = X.columns

plt.figure()
plt.barh(features, importance)
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Features")
plt.show()

# ===============================
# 13. SAVE MODEL
# ===============================
with open("pricing_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("\nModel saved successfully!")